[package]
name = "eipv"
version = "0.0.0"
authors = ["Matt Garnett <matt.garnett@me.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.1"
url = "2.1"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
